import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { MemoryError, type MemoryEntry, type MemoryQuery, type MemoryStore } from '@swt-labs/core';

import { formatIndex, formatTopicFile, parseTopicFile } from './format.js';

export interface FileMemoryStoreOptions {
  /** Root directory containing MEMORY.md and the memory/ subdirectory. */
  readonly dir: string;
}

/**
 * Filesystem-backed MemoryStore.
 *
 * Layout:
 *   <dir>/MEMORY.md           — always-on lightweight index (regenerated by compact())
 *   <dir>/memory/<id>.md      — one topic file per entry, with YAML frontmatter
 */
export class FileMemoryStore implements MemoryStore {
  private readonly dir: string;
  private readonly topicDir: string;
  private readonly indexFile: string;

  constructor(opts: FileMemoryStoreOptions) {
    this.dir = opts.dir;
    this.topicDir = join(opts.dir, 'memory');
    this.indexFile = join(opts.dir, 'MEMORY.md');
  }

  async put(entry: MemoryEntry): Promise<void> {
    if (entry.id.length === 0) {
      throw new MemoryError('MemoryEntry id must be non-empty');
    }
    await mkdir(this.topicDir, { recursive: true });
    await writeFile(this.entryPath(entry.id), formatTopicFile(entry), 'utf8');
    await this.regenerateIndex();
  }

  async get(id: string): Promise<MemoryEntry | undefined> {
    try {
      const raw = await readFile(this.entryPath(id), 'utf8');
      return parseTopicFile(raw).entry;
    } catch (err) {
      if (isFileNotFound(err)) return undefined;
      throw new MemoryError(`Failed to read memory entry ${id}`, { cause: err });
    }
  }

  async query(filter: MemoryQuery): Promise<readonly MemoryEntry[]> {
    let entries = await this.readAllEntries();
    if (filter.topic !== undefined) {
      const topic = filter.topic;
      entries = entries.filter((e) => e.topic === topic);
    }
    if (filter.tag !== undefined) {
      const tag = filter.tag;
      entries = entries.filter((e) => e.tags?.includes(tag) === true);
    }
    if (filter.limit !== undefined && filter.limit >= 0) {
      entries = entries.slice(0, filter.limit);
    }
    return entries;
  }

  async remove(id: string): Promise<void> {
    try {
      await rm(this.entryPath(id), { force: false });
    } catch (err) {
      if (!isFileNotFound(err)) {
        throw new MemoryError(`Failed to remove memory entry ${id}`, { cause: err });
      }
    }
    await this.regenerateIndex();
  }

  async compact(): Promise<void> {
    await this.regenerateIndex();
  }

  private async readAllEntries(): Promise<MemoryEntry[]> {
    let names: string[];
    try {
      names = await readdir(this.topicDir);
    } catch (err) {
      if (isFileNotFound(err)) return [];
      throw new MemoryError('Failed to read memory directory', { cause: err });
    }
    const entries: MemoryEntry[] = [];
    for (const name of names) {
      if (!name.endsWith('.md')) continue;
      try {
        const raw = await readFile(join(this.topicDir, name), 'utf8');
        entries.push(parseTopicFile(raw).entry);
      } catch (err) {
        throw new MemoryError(`Failed to parse topic file ${name}`, { cause: err });
      }
    }
    entries.sort((a, b) => a.id.localeCompare(b.id));
    return entries;
  }

  private async regenerateIndex(): Promise<void> {
    await mkdir(this.dir, { recursive: true });
    const entries = await this.readAllEntries();
    await writeFile(this.indexFile, formatIndex(entries), 'utf8');
  }

  private entryPath(id: string): string {
    return join(this.topicDir, `${sanitiseId(id)}.md`);
  }
}

function sanitiseId(id: string): string {
  return id.replace(/[^A-Za-z0-9._-]/g, '_');
}

function isFileNotFound(err: unknown): boolean {
  return (
    typeof err === 'object' &&
    err !== null &&
    (err as { code?: string }).code === 'ENOENT'
  );
}
