#!/usr/bin/env tsx
/**
 * docs-gen.ts — auto-generate docs/reference/{cli,config,artifacts}.mdx from
 * source. Hand-rolled, no new runtime or dev deps.
 *
 * Plan 05-01 (F6 codegen):
 *   - config.mdx ← ConfigSchema (@swt-labs/core)
 *   - cli.mdx ← buildRegistry (@swt-labs/cli)
 *   - artifacts.mdx ← published Zod schemas (@swt-labs/artifacts)
 *
 * Hand-authored prose lives in docs/reference/_prose/{cli,config,artifacts}.mdx
 * and is inlined at marker comments (`{/* PROSE:override-config-effort *\/}`).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  PlanFrontmatterSchema,
  SummaryFrontmatterSchema,
  RoadmapSchema,
  ResearchFrontmatterSchema,
  RemediationPlanFrontmatterSchema,
  RemediationSummaryFrontmatterSchema,
  ProjectFrontmatterSchema,
} from '@swt-labs/artifacts';
import { buildRegistry } from '@swt-labs/cli';
import { ConfigSchema } from '@swt-labs/core';
import { z, type ZodTypeAny } from 'zod';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = join(__dirname, '..');
const REFERENCE_DIR = join(REPO_ROOT, 'docs', 'reference');
const PROSE_DIR = join(REFERENCE_DIR, '_prose');

const AUTO_GENERATED_HEADER =
  '{/* AUTO-GENERATED by scripts/docs-gen.ts. Do not edit by hand. Edit prose in docs/reference/_prose/. */}\n';

// ─────────────────────────────────────────────────────────────────────────────
// Prose-block extraction
// ─────────────────────────────────────────────────────────────────────────────

interface ProseBlocks {
  readonly [id: string]: string;
}

function loadProseBlocks(file: string): ProseBlocks {
  const raw = readFileSync(file, 'utf8');
  const blocks: Record<string, string> = {};
  const re = /\{\/\*\s*PROSE:([\w-]+)\s*\*\/\}([\s\S]*?)\{\/\*\s*\/PROSE\s*\*\/\}/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(raw)) !== null) {
    const id = match[1] ?? '';
    const body = (match[2] ?? '').trim();
    blocks[id] = body;
  }
  return blocks;
}

function inlineProse(prose: ProseBlocks, id: string): string {
  return prose[id] ?? '_(no override guidance documented)_';
}

// ─────────────────────────────────────────────────────────────────────────────
// Zod type description
// ─────────────────────────────────────────────────────────────────────────────

function describeZodType(schema: ZodTypeAny): string {
  // Unwrap default + optional first to surface the inner type.
  if (schema instanceof z.ZodDefault) {
    return describeZodType(schema._def.innerType as ZodTypeAny);
  }
  if (schema instanceof z.ZodOptional) {
    return `${describeZodType(schema._def.innerType as ZodTypeAny)} (optional)`;
  }
  if (schema instanceof z.ZodEnum) {
    const values = schema._def.values as readonly string[];
    return values.map((v) => `"${v}"`).join(' | ');
  }
  if (schema instanceof z.ZodLiteral) {
    return `"${String(schema._def.value)}"`;
  }
  if (schema instanceof z.ZodString) return 'string';
  if (schema instanceof z.ZodNumber) return 'number';
  if (schema instanceof z.ZodBoolean) return 'boolean';
  if (schema instanceof z.ZodArray) {
    return `${describeZodType(schema._def.type as ZodTypeAny)}[]`;
  }
  if (schema instanceof z.ZodRecord) {
    const valueType = describeZodType(schema._def.valueType as ZodTypeAny);
    return `Record<string, ${valueType}>`;
  }
  if (schema instanceof z.ZodObject) {
    return 'object';
  }
  if (schema instanceof z.ZodUnion) {
    return (schema._def.options as readonly ZodTypeAny[])
      .map((opt) => describeZodType(opt))
      .join(' | ');
  }
  return 'unknown';
}

function defaultValueFor(schema: ZodTypeAny): string | undefined {
  if (schema instanceof z.ZodDefault) {
    const value = (schema._def.defaultValue as () => unknown)();
    return JSON.stringify(value);
  }
  if (schema instanceof z.ZodOptional) {
    return undefined;
  }
  return undefined;
}

// ─────────────────────────────────────────────────────────────────────────────
// generateConfigMdx
// ─────────────────────────────────────────────────────────────────────────────

export function generateConfigMdx(): string {
  const prose = loadProseBlocks(join(PROSE_DIR, 'config.mdx'));
  const lines: string[] = [];
  lines.push(AUTO_GENERATED_HEADER);
  lines.push('---');
  lines.push('title: Configuration reference');
  lines.push(
    'description: Every key in `.swt-planning/config.json` — type, default, when to override.',
  );
  lines.push('---');
  lines.push('');
  lines.push('# Configuration reference');
  lines.push('');
  lines.push(
    '`config.json` lives at `.swt-planning/config.json` and is read on every `swt` invocation. All keys are optional — defaults from `@swt-labs/core/config/defaults.json` apply where missing.',
  );
  lines.push('');

  const shape = ConfigSchema.shape;
  const keys = Object.keys(shape).sort();
  for (const key of keys) {
    const fieldSchema = (shape as Record<string, ZodTypeAny>)[key];
    if (fieldSchema === undefined) continue;
    const typeStr = describeZodType(fieldSchema);
    const defaultStr = defaultValueFor(fieldSchema);
    lines.push(`### \`${key}\``);
    lines.push('');
    lines.push(`- **Type:** \`${typeStr}\``);
    if (defaultStr !== undefined) {
      lines.push(`- **Default:** \`${defaultStr}\``);
    }
    lines.push(`- **When to override:** ${inlineProse(prose, `override-config-${key}`)}`);
    lines.push('');
  }

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// generateCliMdx
// ─────────────────────────────────────────────────────────────────────────────

export function generateCliMdx(): string {
  const prose = loadProseBlocks(join(PROSE_DIR, 'cli.mdx'));
  const lines: string[] = [];
  lines.push(AUTO_GENERATED_HEADER);
  lines.push('---');
  lines.push('title: CLI reference');
  lines.push('description: Every `swt` subcommand registered in the production CLI.');
  lines.push('---');
  lines.push('');
  lines.push('# CLI reference');
  lines.push('');
  lines.push(
    'Generated from the `buildRegistry()` function in `@swt-labs/cli`. Run `swt help` for the live runtime listing.',
  );
  lines.push('');

  const registry = buildRegistry();
  const commands = registry.list();
  for (const cmd of commands) {
    lines.push(`### \`swt ${cmd.name}\``);
    lines.push('');
    lines.push(`${cmd.description}.`);
    lines.push('');
    if (cmd.usage !== undefined) {
      lines.push(`**Usage:** \`swt ${cmd.name} ${cmd.usage}\``);
      lines.push('');
    }
    lines.push(`**Notes:** ${inlineProse(prose, `override-cli-${cmd.name}`)}`);
    lines.push('');
  }

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// generateArtifactsMdx
// ─────────────────────────────────────────────────────────────────────────────

export function generateArtifactsMdx(): string {
  const prose = loadProseBlocks(join(PROSE_DIR, 'artifacts.mdx'));
  const lines: string[] = [];
  lines.push(AUTO_GENERATED_HEADER);
  lines.push('---');
  lines.push('title: Artifacts reference');
  lines.push('description: Frontmatter shapes for every SWT planning artifact.');
  lines.push('---');
  lines.push('');
  lines.push('# Artifacts reference');
  lines.push('');
  lines.push(
    '`@swt-labs/artifacts` exports Zod schemas for every artifact type SWT writes (PLAN.md, SUMMARY.md, VERIFICATION.md, ROADMAP.md, etc.). The schemas listed here are the public surface — they validate every read + write the methodology layer performs.',
  );
  lines.push('');

  const schemas: Array<{ name: string; schema: z.ZodObject<z.ZodRawShape> }> = [
    { name: 'ProjectFrontmatterSchema', schema: ProjectFrontmatterSchema },
    { name: 'RoadmapSchema', schema: RoadmapSchema },
    { name: 'PlanFrontmatterSchema', schema: PlanFrontmatterSchema },
    { name: 'SummaryFrontmatterSchema', schema: SummaryFrontmatterSchema },
    { name: 'ResearchFrontmatterSchema', schema: ResearchFrontmatterSchema },
    { name: 'RemediationPlanFrontmatterSchema', schema: RemediationPlanFrontmatterSchema },
    { name: 'RemediationSummaryFrontmatterSchema', schema: RemediationSummaryFrontmatterSchema },
  ];

  for (const { name, schema } of schemas) {
    lines.push(`### \`${name}\``);
    lines.push('');
    lines.push(`**Notes:** ${inlineProse(prose, `override-artifacts-${name}`)}`);
    lines.push('');
    lines.push('**Fields:**');
    lines.push('');
    const shape = schema.shape;
    const keys = Object.keys(shape).sort();
    for (const key of keys) {
      const field = (shape as Record<string, ZodTypeAny>)[key];
      if (field === undefined) continue;
      lines.push(`- \`${key}\`: \`${describeZodType(field)}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// main
// ─────────────────────────────────────────────────────────────────────────────

export function main(): void {
  writeFileSync(join(REFERENCE_DIR, 'config.mdx'), generateConfigMdx(), 'utf8');
  writeFileSync(join(REFERENCE_DIR, 'cli.mdx'), generateCliMdx(), 'utf8');
  writeFileSync(join(REFERENCE_DIR, 'artifacts.mdx'), generateArtifactsMdx(), 'utf8');
}

if (process.argv[1]?.endsWith('docs-gen.ts')) {
  main();
}
